# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'geekTime_swift_IB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for geekTime_swift_IB
  pod "Kingfisher"
  pod "SnapKit"
  pod "R.swift"

end
